### ISSUE TITLE
Supress D3DERR_INVALIDCALL Error in FLSpew

### ISSUE THREAD

**Issue by IrateRedKite** [TheStarport/FLUF#4]
This error spams in spew constantly when using the alternate renderer. It's not problematic, but makes for very large log files and should probably be suppressed.

**Comment by Lazrius** [comment]
Done in af80177b9fcd7aba61ca0d4f8e8c463aa4e97c06

**Comment by IrateRedKite** [comment]
Still seeing this error in latest nightly. The exact line printed is

`[20250124-15:19:50] C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\dx8_shader_inl.h(84) : WARNING:General:flush_stream_source: D3DERR_INVALIDCALL`

**Comment by Lazrius** [comment]
Changed the detection method from a file hash to a single byte check
058ac3c1179dcf9e40fff97a3af1b84157f1613a
